name: NAM 3km APCP 12–24 Total (NetCDF)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install xarray cfgrib eccodes requests netcdf4

      - name: Run script
        run: |
          python3 nam3km_apcp_12to24_total.py

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: nam3km_apcp_total
          path: nam3km_12z_apcp_f12_f24_total.nc
          
